name: dart_package_examples
description: Simple app with packages.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0-266.1.beta <3.0.0'

dependencies:
  local:
    path: packages/local

dev_dependencies:
  lints: ^2.0.0
